name: Build Windows Executable

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install cx_Freeze


    - name: Clean up cached Python files
      shell: pwsh
      run: |
        Write-Host "Cleaning *.pyc and __pycache__..."
        Get-ChildItem -Recurse -Include *.pyc | Remove-Item -Force -ErrorAction SilentlyContinue
        Get-ChildItem -Recurse -Directory -Filter "__pycache__" | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue


    - name: Build executable with cx_Freeze
      run: |
        python setup.py build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: build/
